# Comments
language: cpp

git:
  depth: 1
  quiet: true

branches:
  only:
    - master

addons:
  apt:
    packages:
      - dos2unix
  homebrew:
    packages:
      - gnu-sed
      - grep
      - dos2unix

matrix:
  include:
    - name: "Linux with GCC"
      os: linux
      dist: bionic
      arch: amd64
      compiler: gcc
    - name: "Linux with clang"
      os: linux
      dist: bionic
      arch: amd64
      compiler: clang
    - name: "macOS"
      os: osx
      osx_image: xcode11.3
      compiler: clang
    - name: "Windows 32"
      os: windows
      env:
        - ARCH=Win32
    - name: "Windows 64"
      os: windows
      env:
        - ARCH=Win64

script:
  # Comments in script
  - pwd
  - echo "TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
  - echo "CC=$CC"
  - echo "GCC=$GCC"

  # Blank line and comments in script
  - echo "CXX=$CXX"
  - echo "ARCH=$ARCH"
  - echo "PATH=$PATH"
  - git log --max-count=2 --format=fuller
  - |-
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        powershell -NoLogo -ExecutionPolicy RemoteSigned ./Build.ps1 -$ARCH -Release
    fi
