os: windows
language: shell

git:
  depth: 1
  quiet: true

install:
  - choco install directx
  - cat /C/ProgramData/chocolatey/logs/chocolatey.log

script:
  - curl -s -L https://github.com/lucasg/Dependencies/releases/latest/download/Dependencies_x64_Release.zip -o Dependencies.zip
  - mkdir dep
  - (cd dep; unzip -q ../Dependencies.zip)
  - dep/Dependencies.exe tsduck/tsversion.exe -modules
  - tsduck/tsversion.exe --version=all
